server:
  port: 8099

# Firebase Config - JWT Issuer URI
spring.security.oauth2.resourceserver.jwt.issuer-uri: https://securetoken.google.com/oscar-venturenix-project

#MySQL Config
spring.datasource:
  driver-class-name: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://localhost:3306/shopping
  username: oscarlo
  password: oscarVenturenixLab2023.
spring.jpa:
  show-sql: true
  hibernate.ddl-auto:
    update
    # create-drop
spring.sql.init:
  mode: always # always
  platform: mysql
spring.profiles.active: enableScheduling
# spring.data.mongodb:
#   host: localhost
#   port: 27017
#   database: Cart_ItemMGD

stripe:
  api:
    publicKey: pk_test_51OUPmzDFIiyCJdlYjDWKaK4ZFKRDqL4HUzfshmgAMgYeTHJKLcSzfNePDDzOPedwbaz3mVszUTONASnl0e69jMlr00jylX6l0e
    secretKey: sk_test_51OUPmzDFIiyCJdlYIRxHYxAXhG9NNbU1uDliUl9tS2gtmFMsw7Qu9t33SuRVGXbuw2itiiit3SRasbVfpLfzXwu600yZ7NaYfz
    webHookSecretKey: whsec_fdf665018bcb44e3539b66cdc25d44cb92f5f28f7c77ed5136b63490e936e778
  currency: USD

#   可发布密钥(pk_test)：前端实现stripe接口时用
# 密钥(sk_test)：后端实现stripe方法时用